main: me.hypermnesia.hyperplugin.Main
name: Hyperplugin
version: 3.1.0
author: Hypermnesia
api-version: 1.13

commands:
  airstrikemarker:
    aliases: asm
  botify:
  changeteam:
  froggielegs:
  getaway:
  hhelp:
  husage:
  launch:
    aliases: lch
  medic:
  omegatrident:
  opaxe:
  pvp:
  skydive:
  suicide:
  discordbot:
  whitefart:
  creator:
  slap:                          